
defaults:
  - _self_
  - agent: residual

experiment: nominal
env:
  robot: hopper
  task: hop
  discount: 0.99
  horizon: 500

checkpoint_dir : checkpoint
num_train_steps: 5e5
seeds: 5
freq_checkpoints: 10
replay_buffer_capacity: ${num_train_steps}

num_steps: 5000
num_epochs: 100
num_eval_episodes: 10
cuda: true
initial_replay_size: 10000
warmup_transitions: 12000
# logger
log_wandb: True
wandb_project: ${experiment}_${env.robot}_${env.task}
wandb_exp_name: ${agent.model.name}




