critic:
  network_class: CriticNetwork
  params:
    n_features: 256
    lr: 1e-4
    critic_tau: 0.005

actor:
  network_class: ActorNetwork
  params:
    n_features: 256
    log_std_bounds: [-20, 2]
    lr: 1e-4


model:
  name: boosted
  critic_cfg: ${critic}
  actor_cfg: ${actor}
  params:
    device: ${device}
    alpha_lr: 1e-4
    batch_size: 256

