model:
  name: sac
  params:
    alpha_lr: 3e-4
    batch_size: 256

critic:
  network_class: CriticNetwork
  params:
    n_features: 256
    lr: 3e-4
    critic_tau: 0.005

actor:
  network_class: ActorNetwork
  params:
    n_features: 256
    log_std_bounds: [-20, 2]
    lr: 1e-4